CREATE TABLE IF NOT EXISTS transformer_stats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    region VARCHAR(10) NOT NULL,
    facility_id VARCHAR(50),
    location TEXT,
    feeder_id VARCHAR(50),
    rate_kva FLOAT,
    kva FLOAT,
    nerr INT,
    loss FLOAT,
    aoj VARCHAR(50),
    name TEXT,
    error_msg TEXT,
    opsa_trsummary_len FLOAT,
    x FLOAT,
    y FLOAT,
    rundate TEXT,
    kva_peak FLOAT,
    pload_peak FLOAT,
    peak_month VARCHAR(50),
    pun_peak FLOAT,
    vmin_peak FLOAT,
    ia_peak FLOAT,
    ib_peak FLOAT,
    ic_peak FLOAT,
    gistag VARCHAR(50),
    datetime_peak TEXT,
    subtypecode INT,
    lat DOUBLE,
    lon DOUBLE,
    ia_rated FLOAT,
    ib_rated FLOAT,
    ic_rated FLOAT,
    pct_ia FLOAT,
    pct_ib FLOAT,
    pct_ic FLOAT,
    pload_kw FLOAT,
    i_load FLOAT,
    max_len FLOAT,
    problem_summary TEXT,
    fix_guideline TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_region (region),
    INDEX idx_facility_id (facility_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
